# This is a basic workflow to help you get started with Actions

name: Crear Dist

# Controls when the action will run.
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      contents: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Use Node.js 14.19.0
        uses: actions/setup-node@v1
        with:
          node-version: 14.19.0

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/checkout@master
      - uses: actions/setup-node@master

      - name: Instalacion de dependencias
        run: npm install

      - name: construccion de dist
        run: npm run build

      - name: Agregar nuevo dist a gh-pages
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          
          git checkout -b newdist
          git add --force dist
          git commit -m "new dist"
          git push -u origin newdist

          # Hacer push del contenido de dist a gh-pages usando subtree
          HASH=$(git subtree split --prefix dist newdist)
          git push origin $HASH:refs/heads/gh-pages --force

          # Limpiar rama temporal
          git push origin --delete newdist
